<a href="https://colab.research.google.com/github/Code-Quasar/TensorFlow_Tuto/blob/main/Hello_World.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
(X_train, y_train), (X_test, y_test) = keras.datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
X_train = X_train / 255
X_test  = X_test / 255

In [ ]:
X_train[1].shape

(28, 28)

In [ ]:
X_train_flattened = X_train.reshape(len(X_train),28*28)
X_test_flatenned = X_test.reshape(len(X_test),28*28)

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(10, activation='sigmoid')
])

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [ ]:
model.fit(X_train_flattened, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8111 - loss: 0.7245
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9119 - loss: 0.3152
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9204 - loss: 0.2842
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.9233 - loss: 0.2725
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.9262 - loss: 0.2626


In [ ]:
model.evaluate(X_test_flatenned, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9127 - loss: 0.3050


[0.2683594524860382, 0.9243999719619751]

In [ ]:
prediction = model.predict(X_train_flattened)

1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step


In [ ]:
prediction[2]

array([6.9710286e-04, 1.3035724e-04, 1.7072459e-01, 6.3401628e-01,
       8.6705714e-01, 5.2996911e-04, 1.9528280e-03, 1.2544122e-01,
       8.8864295e-03, 8.9566238e-02], dtype=float32)

In [ ]:
y_train[2]

np.uint8(4)

In [ ]:
pr = [int(np.argmax(i)) for i in prediction]
print(pr[2])
print(y_train[:4], pr[:4])

4
[5 0 4 1] [5, 0, 4, 1]


In [ ]:
tf.math.confusion_matrix(labels=y_train, predictions=[np.argmax(i) for i in prediction])

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[5764,    1,   19,   12,   10,   34,   42,    9,   24,    8],
       [   1, 6548,   41,   24,    6,   33,    3,   17,   58,   11],
       [  35,   35, 5432,  100,   64,   29,   57,   82,   98,   26],
       [  15,   17,  124, 5595,    5,  194,   15,   55,   59,   52],
       [  14,   26,   34,    9, 5377,    8,   62,   23,   34,  255],
       [  57,   21,   40,  172,   51, 4836,   81,   17,   93,   53],
       [  34,   10,   36,    0,   21,   73, 5723,    3,   17,    1],
       [  12,   22,   65,   24,   36,    7,    3, 5900,   12,  184],
       [  36,  100,   75,  205,   18,  199,   52,   21, 5032,  113],
       [  19,   22,   13,   87,   97,   37,    2,  167,   28, 5477]],
      dtype=int32)>